# Generated by Django 5.2.7 on 2025-10-11 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesotoken',
            name='diplomatura',
        ),
        migrations.RemoveField(
            model_name='accesotoken',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='accesotoken',
            name='tipo',
        ),
        migrations.AddField(
            model_name='accesotoken',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accesotoken',
            name='nivel_destino',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1 (Alumno)'), (2, 'Nivel 2 (Docente)'), (3, 'Nivel 3 (Coordinador)')], default=2),
        ),
        migrations.AlterField(
            model_name='accesotoken',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
