# Generated by Django 5.2.7 on 2025-10-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_remove_accesotoken_diplomatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesotoken',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='asistencias.materia'),
        ),
    ]
