# Generated by Django 5.2.7 on 2025-10-11 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_accesotoken_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomatura',
            name='coordinadores',
            field=models.ManyToManyField(blank=True, related_name='diplos_coordinadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
