# Generated by Django 6.0 on 2025-12-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0005_diplomatura_coordinadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomatura',
            name='municipio',
            field=models.CharField(default='CORONEL ROSALES', max_length=100),
        ),
    ]
