# Generated by Django 6.0 on 2025-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0007_user_phone_number_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='link_clase',
            field=models.TextField(blank=True, help_text='Link o detalle específico para esta clase'),
        ),
        migrations.AddField(
            model_name='materia',
            name='link_clase',
            field=models.TextField(blank=True, help_text='Link o detalle por defecto para las clases'),
        ),
    ]
