# Generated by Django 6.0 on 2025-12-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0008_clase_link_clase_materia_link_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alumno'), (2, 'Docente'), (3, 'Coordinador'), (4, 'Gestor'), (5, 'Administrador'), (6, 'Referente Municipal'), (7, 'Supervisor')], default=1),
        ),
    ]
