# Generated by Django 6.0 on 2025-12-29 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0009_alter_user_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='comentarios_docente',
            field=models.TextField(blank=True, verbose_name='Comentarios del Docente'),
        ),
        migrations.AddField(
            model_name='clase',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='hora_fin',
            field=models.DateTimeField(help_text='Fin ventana asistencia'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='hora_inicio',
            field=models.DateTimeField(help_text='Inicio ventana asistencia'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='link_clase',
            field=models.TextField(blank=True, help_text='Detalle específico'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='link_clase',
            field=models.TextField(blank=True, help_text='Link por defecto'),
        ),
    ]
